
[random]
list = { depth = 20, size = 50 }
val.value = [ "42", "-1" ]
left = { depth = 1, range = [-200, -100] }
right.tree = { depth = 5, range = [100, 200] }
vec.nat8.range = [ 65, 90 ]
Vec = { width = 2, size = 10 }
text = "company"

[random."method:h"]
"arg:0".a.range = [ 42, 42 ]
b.range = [ 0, 1 ]

[random.profile.record]
name.text = "name"
age.range = [ 18, 65 ]
company.text = "company"
country.text = "country"
file.text = "path"
description = "bs"

[random.principal]
value = [ "principal \"aaaaa-aa\"", "principal \"2ibo7-dia\"" ]
