= How to
:!page-repl:

As discussed in link:[], Candid provides a language-agnostic way to interact with canisters.
By using Candid, you can specify input argument values and display return values from canister methods regardless of whether you interact with the {IC} from a terminal using the `+dfx+` command-line interface, through a web browser, or from a program written in JavaScript, {proglang}, Rust, or other language.
Now that you are familiar with what Candid is and how it works, this section provides instructions for how to use it in some common scenarios.

As a concrete example, we assume there is a `counter` canister already deployed on the network with the following
Candid interface:

[source, candid]
....
service Counter : {
  inc : (step: nat) -> (nat);
}
....

We will show how to interact with this canister in various scenarios with the help of Candid.

[[idl-syntax]]
== Interact with a service in a terminal

One of the most common ways you interact with canisters and the {IC} is by using the {company-id} Canister SDK `+dfx+` command-line interface.

The `+dfx+` tool provides the `+dfx canister call+` command to call a specific deployed canister—essentially a service that runs on the {IC}—and, if applicable, a method for that service.

When you run the `+dfx canister call+` command, you can pass arguments to a method by specifying them as link:candid-concepts{outfilesuffix}#textual-values[Candid textual values].

When you pass Candid textual values on the command-line, you can specify multiple argument values separated by commas (`+,+`) and wrapped inside parentheses.
For example, specifying `+(42, true)+` represents two argument values, where the first argument is the number `+42+` and the second argument is a boolean value of `+true+`.

The following example illustrates using the `+dfx canister call+` command to call the `+counter+` canister service and pass arguments for the `+inc+` method:

[source, bash]
....
$ dfx canister call counter inc '(42)'
(43)
....

You can also omit the arguments and let dfx generate a random value that matches the method type:

[source, bash]
....
$ dfx canister call counter inc
Unspecified argument, sending the following random argument:
(1_543_454_453)

(1_543_454_454)
....

For more information about using `+dfx+` and the `+dfx canister call+` command, see link:../developers-guide/cli-reference{outfilesuffix}[Command-line reference] and link:../developers-guide/cli-reference/dfx-canister{outfilesuffix}[dfx canister] documentation.

[[candid-ui]]
== Interact with a service from a browser

The Candid interface description language provides a common language for specifying the signature of a canister service.
Based on the type signature of that service, Candid provides a web interface—the Candid UI—that allows you to call canister functions for testing and debugging from a web browser without writing any front-end code.

To use the Candid web interface to test canister functions:

. Deploy your project using the `+dfx canister install+` command and copy the canister identifier associated with the main program for your application.
. Open a browser and navigate to the address and port number specified in the `+dfx.json+` configuration file.
+
By default, the `+local+` network binds to the `+127.0.0.1:8000+` address and port number.
. Add the `+candid+` endpoint to access the Candid web interface followed by the required `canisterId` parameter and canister identifier.
+
For example, the full URL should look similar to the following but with the `+canister_identifier+` that was returned by the `+dfx canister install+` command:
+
....
http://127.0.0.1:8000/candid?canisterId=<YOUR-CANISTER-IDENTIFIER>
....
. Review the list of function calls and types defined in the program.
. Type a value of the appropriate type for a function or click *Random* to generate a value, then click *Call* or *Query* to see the result.
+
Note that depending on the data type, the Candid interface might display additional configuration settings for testing functions. 
For example, if a function takes an array, you might need to specify the number of items in the array before entering values.

For more information about the tool that creates a Web interface from the Candid interface of any canister, see the link:https://github.com/dfinity/candid/tree/master/tools/ui[Candid UI] repository.

== Interact with a service from a Motoko canister

If you are writing a service in Motoko, the Motoko compiler automatically translates the signature of your canister’s top-level `actor` or `actor class` into a Candid description, and the `+dfx build+` command ensures that the service description is properly referenced where it needs to be.

For example, if you want to write a `hello` canister in {proglang} that calls the `counter` canister in {proglang}:

[source, motoko]
....
import Counter "canister:Counter";
import Nat "mo:base/Nat";
actor {
  public func greet() : async Text {
    let result = await Counter.inc(1);
    "The current counter is " # Nat.toText(result)
  };
}
....

The import dependency of counter canister is handled by `+dfx build+`, which ensures that the canister id and the Candid
description is correctly feed into the {proglang} compiler. The {proglang} compiler then translate the Candid type into
native Motoko type and enables you to call the `inc` method natively, even if the counter canister is implemented in a
different language and you do not have the source code. For additional information on the type mapping
between Candid and {proglang}, you can consult the link:candid-types{outfilesuffix}[Supported types] reference section.

The {proglang} compiler and `+dfx build+` also auto-generate the Candid description for the `hello` canister to allow
other canisters or tools to interact with the `hello` canister seamlessly. The generated Candid description is located
in your project build directory at `.dfx/local/canisters/hello/hello.did`.

== Interact with a service from a Rust canister

If you write a canister in Rust, the `+dfx build+` command ensures that the service description is properly referenced where it needs to be. However, you need to write the Candid service description manually following the conventions described in the link:https://github.com/dfinity/candid/blob/master/spec/Candid.md#core-grammar[Candid specification].

For example, if you want to write a `hello` canister in {proglang} that calls the `counter` canister in {proglang}:

[source, rust]
....
use ic_cdk_macros::*;

#[import(canister = "counter")]
struct Counter;

#[update]
async fn greet() -> String {
    let result = Counter::inc(1.into()).await;
    format!("The current counter is {}", result)
}
....

The import dependency of counter canister is handled by `+dfx build+`, which ensures that the canister id and the Candid
description is correctly feed into the Rust CDK. The Rust CDK then translate the Candid type into
native Rust type and enables you to call the `inc` method natively, even if the counter canister is implemented in a
different language and you do not have the source code. For additional information on the type mapping
between Candid and Rust, you can consult the link:candid-types{outfilesuffix}[Supported types] reference section.

For other canisters and tools to interact with the `hello` canister, you need to manually create a `.did` file:

[source, candid]
....
service : {
    greet : () -> (text);
}
....

There is also an experimental feature to generate Candid service description automatically, see this https://github.com/dfinity/candid/blob/master/rust/candid/tests/types.rs#L99[test case] as an example.

For additional information and libraries to help you create Candid services or canisters in Rust, see the documentation for the https://docs.rs/candid/[Candid crate], link:https://github.com/dfinity/cdk-rs/tree/next/examples[Rust CDK examples] and the link:../rust-guide/rust-intro{outfilesuffix}[Rust tutorials].

== Interact with a service from JavaScript

The https://www.npmjs.com/package/@dfinity/agent[dfinity/agent npm package] includes support for
importing canisters via Candid.

For example, if you want to call the `counter` canister, you can write the following JavaScript program:

[source, javascript]
....
import counter from 'ic:canisters/counter';
import BigNumber from 'bignumber.js';
async () => {
  const result = await counter.inc(new BigNumber(42));
  console.log("The current counter is " + result.toString());
}
....

The import dependency of counter canister is handled by `+dfx build+` and `webpack`, which ensures that the canister id and the Candid description is correctly feed into the JavaScript program. Behind the scenes, the Candid service description is
translated into a JavaScript module, located at `.dfx/local/canister/counter/counter.did.js`, by `+dfx build+`. The `dfinity/agent` package then translate the Candid type into
native JavaScript values and enables you to call the `inc` method natively, even if the counter canister is implemented in a
different language and you do not have the source code. For additional information on the type mapping
between Candid and JavaScript, you can consult the link:candid-types{outfilesuffix}[Supported types] reference section.

== Create a new Candid implementation

In addition to the Candid implementations for Motoko, Rust, and JavaScript, there are community-supported Candid libraries for the following host languages:

* link:https://hackage.haskell.org/package/candid[Haskell]
* link:https://github.com/chenyan2002/ic-elm/[Elm]
* link:https://github.com/seniorjoinu/candid-kt[Kotlin]
* link:https://github.com/rckprtr/cdk-as/tree/master/packages/cdk/assembly/candid[AssemblyScript]

If you want to create a Candid implementation to support a language or tool for which an implementation is not currently available, you should consult the https://github.com/dfinity/candid/blob/master/spec/Candid.md[Candid specification].

If you add a Candid implementation for a new language or tool, you can use the official https://github.com/dfinity/candid/tree/master/test[Candid test data] to test and verify that your implementation is compatible with Candid, even in slightly more obscure corner cases.
