[package]
name = "didjs"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.5"
ic-cdk-macros = "0.5"
candid = "0.7"
serde = "1.0"
serde_bytes = "0.11"
