[package]
name = "didjs"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { version = "0.10", git = "https://github.com/dfinity/cdk-rs.git", branch = "beta" }
candid = { version = "0.9", features = ["parser"] }
serde = "1.0"
serde_bytes = "0.11"

