= Candid User’s guide

Welcome to the Candid’s user guide. This document will explain what Candid is, what it can do for you, and how you use it.

NOTE: The primary target audience is Candid _users_, i.e. canister and front-end developers.
If you are about to _implement_ Candid, want to learn about its internals or its meta-theory, you should look at the [Candid specification].

== What is Candid?

Candid is an _Interface description language_, and is used to describe the public interface of a service (such a caniter running on the Internet Computer). It is language agnostic, and thus allows seamless interoperation between services and front-ends written different programming languages (Motoko, Rust, JavaScript, etc.)

A typical interface description in Candid looks as follows:
....
service counter : {
  add : (nat) -> ();
  subtract : (nat) -> ();
  get : () -> (int) query;
  subscribe : (func (int) -> ()) -> ();
}
....

This says that the described service has four public methods. Two to change the value of a a counter, one to read the current value, and one that can be used to pass a method, presumably to be invoked upon each change of the counter.

Every method has a sequence of argument and result types, and Internet-Computer specific annotations (such as `query`) are supported.

Given this interface description, it is possible to interact with this service seamlessly from the command line, from a generic web interface, from Rust code etc.

Furthermore, Candid supports the evolution of service interfaces: It precisely specifies which changes (such as adding new optional parameters) can be made, without breaking existing clients.

== Why create a new IDL?

At first glance one may think that prior technologies, like JSON, XML, Protobuf etc., would suffice. However, Candid provides a certain combination of features that are not found in these technologies, and that are very valuable when developing on the Internet Computer.

* JSON, XML etc. are merely data description languages. They describe how to map the values that we want to transfer to bytes or characters, but they do not describe the services as a whole.

* Candid implementations map the Candid value directly to types and values of the host language; in Candid, programmers do not construct or deconstruct some abstract `Candid` value.

* Candid defines what is a “safe upgrade” in a sound and compositional way.

* Candid is inherently higher order: You can pass not just plain data, but also references to services and methods, which is an important feature on the Intenet Computer. Furthermore, Candid’s notion of safe upgrades takes such higher-order use into account.

* Candid as built-in support for Internet-Computer specific features, such as the `query` annotation.

== Concepts and workflows

This section introduces various concepts around Candid, and how they play together. This gives you a good overview and enables you to decide how to best apply Candid to your usecase. With that knowledge, the <<how-do-i,following section>> explains typical workflows. Exhaustive documentation follows in the <<reference,reference section>>.

=== Candid types and values

Candid is a strongly typed system with a set of types that canonically cover most uses. It has:

 * Unbounded integral number types (`nat`, `int`)
 * Bounded integral number (`nat8`,`nat16`, `nat32`, `nat64`, `int8`,`int16`, `int32`, `int64`)
 * Floating point types (`float32`, `float64`)
 * The Boolean type (`bool`)
 * Types for textual (`text`) and binary (`blob`) data
 * Container types, including variants (`opt`, `vec`, `record`, `variant`)
 * Reference types (`service`, `func`, `principal`)
 * The special `null`, `reserved` and `empty` types

All types are described in detail in the <<reference, reference section>>.

The philosophy behind this set of types is that they are sufficient to describe the _structure_ of data, so that information can be encoded, passed around and decoded, but intentionally do not describe _semantics_ constraints beyond what’s needed to describe the representation (e.g. no way to express that a numer should be even, or that the elements of a vector are sorted).

Furthermore, the set of types is chosen to allow a resonably intuitive mapping to the respective host language (Motoko, Rust, JavaScript, etc.), thus settling on very canonic choices.

[#candid-service-descriptions]
=== Candid service descriptions

With these candid types, we now can describe a service. Such a service description file can be written by hand, but typically it is generated from the service implementation, as described later.

The simplest service description is
....
service : {}
....
and describes a service with no public methods. This is not very useful, so lets add a simple method:
....
service : {
  ping : () -> ();
}
....

This says that the service supports a public method called `ping`. Method names can be arbitrary strings, and you can quote them (`"method with spaces"`) if they are not plain identifiers.

Methods declare a _sequence_ of arguments and result types. In the case of `ping`, no arguments are passed and none are returned, so the empty sequence `()` is used. We can extend that:
....
service : {
  reverse : (text) -> (text);
  divMod : (dividend : nat, divisor : nat) -> (div : nat, mod : nat);
}
....

The method `reverse` expects a single parameter of type `text` and returns one value of type `text`.

The method `divMod` expects and returns two values, all of type `int`. In its signature, we use the ability to name the parameters and result values.

[CAUTION]
====
Naming the parameters or results of a method is purely for documentation purposes, but does not actually change the method’s type, or the values being passed. Parameter and results are identified by their _position_, independent of the name.

In particular, Candid will does not prevent you from changing the type to
....
  divMod : (dividend : nat, divisor : nat) -> (mod : nat, div : nat);
....
or passing the above `divMod` to a service expeting a method that returns `mod` first.

This is thus very different from named _record_ fields, which are semantically relevant.
====

Often, multiple methods in a service may refer to the same complex type. In that case, the type can be named and reused multiple times:
....
type address = record {
  street : text;
  city : text;
  zip_code : nat;
  country : text;
};
service address_book : {
  set_address: (name : text, address) -> ();
  get_address: (name : text) -> (opt address) query;
}
....

In this example, we also see the use of the `query` annotation. This Internet-Computer specific annotation indicates that the method `get_address` can be invoked using a query call (TODO: reference general documentation about query calls here)

=== Encoding and decoding

The point of Candid is to allow seamless invocation of service methods, passing arguments encoded to a binary format and transferred by an underlying transporation method (such as messages into or within the Internet Computer), and decoded on the other side.

As a Candid user, you do not have to worry about the details of this binary format. If you plan to _implemnet_ Candid yourself (e.g. for a new host language), you can consult the Candid specification for details. However, some aspects of the format are worth knowing:

* The Candid binary format starts with `DIDL…` (or, in hex, `4449444c…`). If you see this in some low-level log output, you are very likely observing a Candid-encoded value.

* The Candid binary format always encodes _sequences_ of values, because methods parameters and results are sequences of types.

* The binary format is quite compact. A `(vec nat64)` with 125000 entries takes 1000007 bytes.

* The binary is self-describing, and includes a (condended) description of type of the values therein. This allows the receiving side to detect if a message was sent at a different, incompatible type.

* As long as the sending side serializes the arguments at the same type that the receiving side expects them, deserialization will succeed.

=== Service upgrades

Services evolve over time: They gain new methods, existing methods return more data, or expect additional arguments. Usually, service authors want to do that without breaking existing clients.

Candid supports such evolution by defining precise rules that indicate when the new service type will still be able to communicate with all other parties that are using the previous interface description. The underlying formalim is that of _subtyping_.

Services can safely evolve in the following ways:

 * New methods can be added.
 * Existing methods can return additional values, i.e. the sequence of result types can be extended. Old clients will simply ignore additional values.
 * Existing methods can shorten their parameter list. Old clients may still send the extra arguments, but they will be ignored.
 * Existing methods can extend their parameter list with optional arguments (type `opt …`). When reading messages from old clients, who do not pass that argument, a `null` values is assumed.
 * Existing parameter types may be _changed_, but only to a _supertype_ of the previous type.
 * Existing result types may be _changed_, but only to a _subtype_ of the previous type.

See the reference sections the supertypes and subtypes of a given type.

[TIP]
====
Consider a serivce with the following API:
....
service counter : {
  add : (nat) -> ();
  subtract : (nat) -> ();
  get : () -> (int) query;
  subscribe : (func (int) -> ()) -> ();
}
....
This can evolve to the following interface:
....
type timestamp = nat;
service counter : {
  set : (nat) -> ();
  add : (int) -> (new_val : nat);
  subtract : (nat, trap_on_underflow : opt bool) -> (new_val : nat);
  get : () -> (nat, last_change : timestamp) query;
  subscribe : (func (nat) -> (unregister : opt bool)) -> ();
}
....
====

[#textual-values]
=== Candid textual values

The main purpose of Candid is to connect programs written in some host language (Motoko, Rust, JavaScript, etc.), and developers therefore usually do not have to deal with “Candid values” per se: They work with, say, JavaScript values that are then, transparently and seamelessly, transported to a canister written in Rust, where they show up as Rust values.

Nevertheless there are use cases where it is helpful to see the Candid values per se, e.g. for logging, debugging, or command-line interaction with services. In this cases, the _textual presentation_ for Candid values can be used.

The syntax is similar to that of candid types. A typical candid value might read
....
(record {
  first_name = "John";
  last_name = "Doe";
  age = 14;
  membership_status = variant { active };
  email_addresses =
    vec { "john@doe.com"; "john.doe@example.com" };
})
....

[NOTE]
====
The Candid _binary_ format does not include the actual field names, merely numeric _hashes_. So pretty-printing such a value without knowledge of the expected type will not include the field names of records and variants. The above value might then be printed as
....
(record {4846783 = 14; 456245371 = variant {373703110}; 1443915007 = vec {"john@doe.com"; "john.doe@example.com"}; 2797692922 = "John"; 3046132756 = "Doe"})
....
====

=== Generating service descriptions

In the <<candid-service-descriptions,section above>> you learned how to write a Candid service description from scratch. But often, that is not even needed! Depending on the language you use to implement your service, you can get the Candid service description generated from your code.

For example, in Motoko, you can write a canister as
....
actor {
  var v : Int = 0;
  public func add(d : Nat) : async () { v += d; };
  public func subtract(d : Nat) : async () { v -= d; };
  public query func get() : async Int { v };
  public func subscribe(handler : func (Int) -> async ()) { … }
}
....
and it will have the interface shown above.

In other languages, like Rust, you can still develop your service while only
touching Rust types, but for now you still have to write the Candid interface description manually.

In either case it is helpful to know the mapping between host language types and Candid types; this mapping is describeed in the <<reference, reference section>>.

=== Candid tools and libraries

The Motoko language has built-in support for Candid.

To create Candid services or clients in Rust, you can use the https://crates.io/crates/candid[Candid crate].

The https://github.com/dfinity/agent-js/[Internet Computer agent library for JavaScript] includes support for Candid.

Community-supported libaries for Candid exist for https://hackage.haskell.org/package/candid[Haskell], https://github.com/chenyan2002/ic-elm/[Elm] and https://github.com/seniorjoinu/candid-kt[Kotlin].

The https://github.com/dfinity/candid/tree/master/tools/ui[Candid UI] creates a Web interface from the Candid interface of any canister.


[#how-do-i]
== How do I…

Now that you have a good overview of Candid and its various moving parts, this section gives you concrete instructions to achieve certain tasks.

=== Interact with canisters on the command line?

The `dfx` tool provides the `dfx canister call` command, which understands <<textual-values,Candid textual values>>:
....
dfx canister call msgt2-6nlzx-xq add_entry ("John Doe", record { street = "Hauptstraße", city = "Zürich" })
....

See TODO to read more about how to use the `dfx` tool.

=== Interact with canisters via Candid UI?

=== Use Candid as a Motoko canister developer?

If you are writing a service from scratch in Motoko, then you need to take no special actions: The Motoko compiler will translate the signature of your Canister’s top-level actor or actor class into a Candid description, and the `dfx` build tool will make sure it ends up where it needs to be.

If you want to implement a _specific_ interface, for example because you want to interact with a service that expects your canister to have that interface, you can consult the 
reference below to figure which Motoko types to use to achieve this effect. In the future, this will be simplified.

=== Use Candid as Rust canister developer?

TODO: Someone who implements rust canisters should write this section.

=== Use Candid as a JavaScript front-end developer?

TODO: Someone who implements Frontends should write this section

[#reference]
== Reference

This section lists all the types supported by Candid, including their type syntax, the syntax for the textual representation, their upgrading rules and the corresponding types in Rust, Motoko and Javascript.

We only list the particular subtypes and supertypes in each section, and do not repeat everyt that that the type `empty` is a subtype of any type, and that the types `reserved` and `opt t` are supertypes of any types. See the sections on these types for more details.

[#type-text]
=== `text`

The `text` type is used for human readable text. More precisely, its values are sequences of unicode code points (excluding surrogate parts).

Type syntax::

`text`

Textual syntax::

....
""
"Hello"
"Escaped characters: \n \r \t \\ \" \'"
"Unicode escapes: \u{2603} is ☃"
"Raw bytes (must be utf8): \E2\98\83 is also ☃"
....

Corresponding Motoko type::

`Text`

Corresponding Rust type::

`String`

Corresponding JavaScript values::

TODO:

[#type-blob]
=== `blob`

The `blob` type can be used for binary data, i.e. sequences of bytes. It is interchangable with `vec nat8`, i.e. interfaces written in terms of `blob` and interfaces written in terms of `vec nat8` are compatible.

Type syntax::

`blob`

Textual syntax::

`blob <text>`, where `<text>` is a text literal (see <<type-text,above>>), with all characters representing their utf8 encoding, and arbitray byte sequences (`"\CA\FF\FE"`).

Subtypes::

`vec nat8`, and all subtypes of that.

Supertypes::

`vec nat8`, and all supertypes of that.

Corresponding Motoko type::

`Blob`

Corresponding Rust type::

`Vec<u8>`

Corresponding JavaScript values::

TODO:

[#type-nat]
=== `nat`

[#type-int]
=== `int`

[#type-natN]
[#type-intN]
=== `natN` and `intN`

[#type-bool]
=== `bool`

[#type-vec]
=== `vec t`

The `vec` type representes vectors (sequences, lists, arrays): A value of type `vec t` contains zero or more values of type `t` in a specific order

Type syntax::

`vec bool`, `vec nat8`, `vec vec text`,…

Textual syntax::

....
vec {}
vec { "john@doe.com"; "john.doe@example.com" };
....

Subtypes::

* Whenever `t` is a subtype of `t'`, then `vec t` is a subtype of `vec t'`.
* `blob` is a subtype of `vec nat8`

Supertypes::

* Whenever `t` is a supertype of `t'`, then `vec t` is a supertype of `vec t'`.
* `blob` is a supertype of `vec nat8`

Corresponding Motoko type::

`[T]`, where the Motoko type `T` corresponds to `t`

Corresponding Rust type::

`Vec<T>`, where the Rust type `T` corresponds to `t`

Corresponding JavaScript values::

TODO:

=== `opt`

=== `record`

=== `variant`

=== `func`

=== `service`

=== `principal`

=== `null`

=== `reserved`

=== `empty`

The `empty` type is the type without values, and is the subtype of any other type.

Type syntax::

`empty`

Textual syntax::

None, as this type has no values

Supertypes::

Any type

Corresponding Motoko type::

`None`

Corresponding Rust type::

TODO

Corresponding JavaScript values::

TODO

Practical uses of the `empty` type are relatively rare.
It could be used to mark a method as “never returns successful”:
....
service : {
  always_fails () -> (empty)
}
....


