name: Release
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            name: linux64
            artifact_name: target/x86_64-unknown-linux-musl/release/didc
            asset_name: didc-linux64
          - os: macos-15-intel
            name: macos
            artifact_name: target/release/didc
            asset_name: didc-macos
          - os: ubuntu-22.04
            name: arm
            artifact_name: target/arm-unknown-linux-gnueabihf/release/didc
            asset_name: didc-arm32
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Add arm target
        if: matrix.name == 'arm'
        run: rustup target add arm-unknown-linux-gnueabihf
      - name: Build
        if: matrix.name == 'linux64'
        run: |
          set -x
          sudo apt-get update -yy
          sudo apt-get install -yy musl musl-dev musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo build --package didc --release --locked --target x86_64-unknown-linux-musl
      - name: Build
        if: matrix.name == 'macos'
        run: cargo build --package didc --release --locked
      - name: Cross build
        if: matrix.name == 'arm'
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          use-cross: true
          command: build
          args: --package didc --target arm-unknown-linux-gnueabihf --release --locked
      - name: "Upload assets"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
          retention-days: 3
  test:
    needs: build
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            asset_name: didc-linux64
          - os: ubuntu-22.04
            asset_name: didc-linux64
    steps:
      - name: Get executable
        id: download
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ matrix.asset_name }}
      - name: Executable runs
        run: |
          chmod +x didc
          ./didc --version
  publish:
    needs: test
    name: Publish ${{ matrix.asset_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - asset_name: didc-linux64
          - asset_name: didc-arm32
          - asset_name: didc-macos
    runs-on: ubuntu-latest
    steps:
      - name: Get executable
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ matrix.asset_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: didc
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

  candid-ui:
    name: Build and publish candid_ui canister
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
      - name: Install Rust toolchain
        run: rustup show active-toolchain || rustup toolchain install
      - name: Install binaryen
        run: |
          sudo apt-get update -yy
          sudo apt-get install -yy binaryen
      - name: Build candid_ui
        working-directory: tools/ui
        run: |
          npm install
          npm run build
          cargo build --target wasm32-unknown-unknown --profile canister --package didjs
          wasm-opt --strip-debug -Oz target/wasm32-unknown-unknown/canister/didjs.wasm -o target/wasm32-unknown-unknown/canister/didjs_opt.wasm
      - name: Prepare asset
        run: |
          cp tools/ui/target/wasm32-unknown-unknown/canister/didjs_opt.wasm candid_ui.wasm
      - name: Upload candid_ui to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: candid_ui.wasm
          asset_name: candid_ui.wasm
          tag: ${{ github.ref }}
