name: Tools

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always # Force Cargo to use colors
  TERM: xterm-256color
  WORKING_DIR: tools/didc-js

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: dfinity/ci-tools/actions/setup-pnpm@4b6df5046ffab822abcfef2af5aec2c33e419d02
        with:
          working-directory: ${{ env.WORKING_DIR }}

      - name: Build didc-js
        run: pnpm build

      - name: Test didc-js
        run: pnpm test
