name: Tools
on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always # Force Cargo to use colors
  TERM: xterm-256color

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: tools/didc-js
    steps:
      - uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Build didc-js
        run: pnpm build

      - name: Test didc-js
        run: pnpm test
