name: Tools

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always # Force Cargo to use colors
  TERM: xterm-256color
  WORKING_DIR: tools/didc-js

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - name: "Setup PNPM"
        uses: dfinity/ci-tools/actions/setup-pnpm@4a9ed3a6c8fb04ec11b9af8e013a10411236860c
        with:
          working_directory: ${{ env.WORKING_DIR }}

      - name: Build didc-js
        run: pnpm build

      - name: Test didc-js
        run: pnpm test
